### ISSUE TITLE
openAPIからスキーマを自動作成

### ISSUE THREAD

**Issue by shinamon610** [protomo-friends/Acoboo#15]
今各ページで適当にスキーマを定義して使っているが、OpenAPIのyamlファイルから自動作成する。

**Comment by sysnote8main** [comment]
現時点では、フロントエンドのみしか実装されていないため、とりあえずフロントエンドの生成のみ対応する。

**Comment by sysnote8main** [comment]
#21 がマージされたので、frontendのラベルは外しました。
