### ISSUE TITLE
ドキュメントをどこに書くか

### ISSUE THREAD

**Issue by shinamon610** [protomo-friends/Acoboo#2]

**Comment by sysnote8main** [comment]
> このリポジトリをPublicにすることで諸々の機能を使えるため、 ちゃははんがPublicにしました(Private を希望してたしおんさんとは合意を握りました) Github Wikiを使える状態になったため、ドキュメントの置き場は当初の合意通りGithub Wikiが良いと思うのですがどうでしょう？ @sysnote8main

私もGithub Wikiで良いと思うので、Github Wikiで行きましょう！

**Comment by shinamon610** [comment]
okです!
github wikiに書くってことでcloseします。
